@extends('layouts.admin')

@section('title', 'API Keys')
@section('page-title', 'API Keys')

@push('breadcrumbs')
    <li class="breadcrumb-item active">API Keys</li>
@endpush

@section('content')
    <div class="card">
        <div class="card-header">
            <p class="text-muted mb-0">API keys are generated by users from their account. Admins may deactivate or revoke keys here.</p>
        </div>
        <div class="card-body">
            <table id="apiKeysTable" class="table table-bordered table-striped w-100">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Key Prefix</th>
                        <th>User</th>
                        <th>Active</th>
                        <th>Rate Limit / min</th>
                        <th>Last Used</th>
                        <th>Expires</th>
                        <th style="width:120px;">Actions</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
<script>
$(function () {
    AdminCRUD.initDataTable('#apiKeysTable', {
        ajaxUrl: '{{ route("admin.api-keys.data") }}',
        order: [[5, 'desc']],
        columns: [
            { data: 'name', name: 'name' },
            { data: 'key_prefix', name: 'key_prefix' },
            { data: 'user', name: 'user_id', orderable: false },
            {
                data: 'is_active', name: 'is_active', orderable: false,
                render: (v, t, row) => `<button class="btn btn-sm btn-toggle-active ${v ? 'btn-success' : 'btn-outline-secondary'}" data-id="${row.id}">${v ? 'Active' : 'Inactive'}</button>`,
            },
            { data: 'rate_limit_per_minute', name: 'rate_limit_per_minute' },
            { data: 'last_used_at', name: 'last_used_at', defaultContent: '-' },
            { data: 'expires_at', name: 'expires_at', defaultContent: '-' },
            {
                data: null, orderable: false, searchable: false,
                render: (row) => `
                    <div class="table-actions">
                        <button class="btn btn-sm btn-danger btn-delete" data-id="${row.id}" data-name="${row.name}"><i class="fas fa-trash"></i></button>
                    </div>`,
            },
        ],
    });

    AdminCRUD.bindDelete('.btn-delete', (id) => `{{ url('admin/api-keys') }}/${id}`, { text: 'This will permanently revoke the API key.' });
    AdminCRUD.bindToggle('.btn-toggle-active', (id) => `{{ url('admin/api-keys') }}/${id}/toggle-active`);
});
</script>
@endpush
