<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $calculator->title }} — Result</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1A1A1A; font-size: 13px; }
        .header { border-bottom: 3px solid #0B6E4F; padding-bottom: 12px; margin-bottom: 20px; }
        .brand { font-size: 20px; font-weight: bold; color: #0B6E4F; }
        h1 { font-size: 18px; margin: 10px 0 4px; }
        .muted { color: #5C6B73; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 14px; }
        th, td { padding: 8px 10px; border: 1px solid #e2e2e2; text-align: left; font-size: 12px; }
        th { background: #F7F9F8; width: 45%; }
        .metric { display: inline-block; width: 48%; background: #F7F9F8; border-radius: 8px; padding: 10px 14px; margin: 4px 0; }
        .metric-label { font-size: 10px; text-transform: uppercase; color: #5C6B73; }
        .metric-value { font-size: 20px; font-weight: bold; color: #084C37; }
        .footer { margin-top: 30px; font-size: 10px; color: #5C6B73; border-top: 1px solid #e2e2e2; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">AI Calculator Hub</div>
        <h1>{{ $calculator->title }}</h1>
        <div class="muted">Generated on {{ $generatedAt->format('M d, Y H:i') }}</div>
    </div>

    <h3>Result</h3>
    @foreach($results as $key => $value)
        <div class="metric">
            <div class="metric-label">{{ ucwords(str_replace('_', ' ', $key)) }}</div>
            <div class="metric-value">{{ is_array($value) ? json_encode($value) : $value }} {{ $units[$key] ?? '' }}</div>
        </div>
    @endforeach

    @if(!empty($breakdown))
        <h3>Breakdown</h3>
        <table>
            @foreach($breakdown as $key => $value)
                <tr>
                    <th>{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                    <td>{{ is_array($value) ? json_encode($value) : $value }} {{ $units[$key] ?? '' }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    @if(!empty($inputs))
        <h3>Inputs Used</h3>
        <table>
            @foreach($inputs as $key => $value)
                <tr>
                    <th>{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                    <td>{{ is_array($value) ? json_encode($value) : $value }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    <div class="footer">
        Generated by AI Calculator Hub — {{ url('/calculator/'.$calculator->slug) }}
    </div>
</body>
</html>
