<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Concerns\BuildsDataTableResponse;
use App\Http\Controllers\Controller;
use App\Models\ApiKey;
use App\Services\Activity\ActivityLogService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Admin-facing, read-mostly view of API keys issued to users. Keys are
 * generated by users themselves; admins can inspect, deactivate, or revoke.
 */
class ApiKeyController extends Controller
{
    use BuildsDataTableResponse;

    public function __construct(protected ActivityLogService $activityLog)
    {
    }

    public function index(): View
    {
        return view('admin.api-keys.index');
    }

    public function data(Request $request): JsonResponse
    {
        $query = ApiKey::query()->with('user');

        return $this->toDataTableResponse(
            $request,
            $query,
            searchableColumns: ['name', 'key_prefix'],
            orderableColumns: ['name', 'user_id', 'is_active', 'rate_limit_per_minute', 'last_used_at', 'created_at'],
            transform: function (ApiKey $key) {
                return [
                    'id' => $key->id,
                    'name' => $key->name,
                    'key_prefix' => $key->key_prefix,
                    'user' => $key->user?->name,
                    'is_active' => (bool) $key->is_active,
                    'rate_limit_per_minute' => $key->rate_limit_per_minute,
                    'last_used_at' => $key->last_used_at?->format('Y-m-d H:i'),
                    'expires_at' => $key->expires_at?->format('Y-m-d'),
                ];
            }
        );
    }

    public function toggleActive(int $id): JsonResponse
    {
        $key = ApiKey::findOrFail($id);
        $key->update(['is_active' => ! $key->is_active]);

        $this->activityLog->log('toggle', 'api_keys', $key, ['is_active' => $key->is_active]);

        return response()->json(['message' => 'API key status updated successfully.', 'data' => $key]);
    }

    public function destroy(int $id): JsonResponse
    {
        $key = ApiKey::findOrFail($id);
        $name = $key->name;
        $key->delete();

        $this->activityLog->log('revoke', 'api_keys', null, ['name' => $name]);

        return response()->json(['message' => 'API key revoked successfully.']);
    }
}
